-- Schema awal untuk aplikasi Diskominfo yang saat ini memakai node-postgres (pg).
-- Jalankan HANYA pada project Supabase BARU/KOSONG setelah meninjau file ini.
-- Skrip ini tidak menghapus tabel atau data. CREATE TABLE IF NOT EXISTS juga tidak
-- mengubah kolom pada tabel lama; jangan gunakan sebagai migrasi untuk database aktif.
--
-- Mode koneksi: Next.js server -> PostgreSQL Supabase menggunakan DATABASE_URL.
-- Login aplikasi tetap dikelola tabel public.users (bcrypt/JWT), bukan Supabase Auth.
-- RLS aktif tanpa policy API publik: anon/authenticated tidak mendapat akses baris.
-- Koneksi server menggunakan kredensial database rahasia yang memiliki hak ke tabel.

BEGIN;

CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  password text NOT NULL,
  role varchar(50) NOT NULL DEFAULT 'admin-kelurahan'
    CHECK (role IN ('super-admin', 'admin-dinas', 'admin-kecamatan', 'admin-kelurahan')),
  instansi varchar(255) NOT NULL DEFAULT '',
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb
    CHECK (jsonb_typeof(permissions) = 'array'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL UNIQUE,
  description text,
  preview_image varchar(1000),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.websites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  name varchar(255) NOT NULL,
  description text,
  subdomain varchar(255) NOT NULL,
  domain varchar(255),
  template_id bigint REFERENCES public.templates(id) ON DELETE RESTRICT,
  status varchar(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'suspended')),
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- Sesuai dengan pemeriksaan subdomain yang mengabaikan website soft-deleted.
CREATE UNIQUE INDEX IF NOT EXISTS websites_subdomain_live_uidx
  ON public.websites (lower(subdomain))
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS websites_user_live_idx
  ON public.websites (user_id, created_at DESC)
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS websites_template_live_idx
  ON public.websites (template_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.menu_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL UNIQUE,
  "order" integer NOT NULL DEFAULT 0,
  available_for text[] NOT NULL DEFAULT ARRAY['dinas', 'kecamatan', 'kelurahan'],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  menu_item_id bigint NOT NULL REFERENCES public.menu_items(id) ON DELETE RESTRICT,
  title varchar(255),
  body text,
  images jsonb NOT NULL DEFAULT '[]'::jsonb,
  files jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contents_website_menu_unique UNIQUE (website_id, menu_item_id)
);
CREATE INDEX IF NOT EXISTS contents_website_idx ON public.contents (website_id);

CREATE TABLE IF NOT EXISTS public.news_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  url varchar(1000) NOT NULL,
  title varchar(500),
  author varchar(255),
  image varchar(1000),
  excerpt text,
  source_domain varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  body text NOT NULL,
  publish_date date NOT NULL,
  expires_at date,
  attachment_path text,
  attachment_name varchar(255),
  attachment_type varchar(100),
  attachment_size bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT announcements_valid_period CHECK (expires_at IS NULL OR expires_at >= publish_date)
);
CREATE INDEX IF NOT EXISTS announcements_website_publish_idx
  ON public.announcements (website_id, publish_date DESC);

CREATE TABLE IF NOT EXISTS public.innovations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  description text NOT NULL,
  launch_year smallint,
  application_url text,
  video_url text,
  cover_path text,
  cover_name varchar(255),
  cover_type varchar(100),
  cover_size bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT innovations_launch_year_valid CHECK (launch_year IS NULL OR launch_year BETWEEN 1990 AND 2099)
);
CREATE INDEX IF NOT EXISTS innovations_website_created_idx
  ON public.innovations (website_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.agendas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  description text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  time_range varchar(100),
  location varchar(500),
  organizer varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agendas_valid_period CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS agendas_website_start_idx
  ON public.agendas (website_id, start_date, created_at DESC);

CREATE TABLE IF NOT EXISTS public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  category varchar(50) NOT NULL CHECK (category IN ('kependudukan', 'sosial', 'perizinan', 'pemerintahan')),
  description text NOT NULL,
  requirements text,
  procedure text,
  completion_time varchar(150),
  fee varchar(150),
  application_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS services_website_category_created_idx
  ON public.services (website_id, category, created_at DESC);

CREATE INDEX IF NOT EXISTS news_items_website_created_idx
  ON public.news_items (website_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.gallery_albums (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  type varchar(20) NOT NULL CHECK (type IN ('image', 'video')),
  title varchar(255) NOT NULL,
  album_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS gallery_albums_website_type_idx
  ON public.gallery_albums (website_id, type);

CREATE TABLE IF NOT EXISTS public.gallery_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gallery_album_id bigint NOT NULL REFERENCES public.gallery_albums(id) ON DELETE CASCADE,
  type varchar(20) NOT NULL CHECK (type IN ('image', 'video', 'youtube')),
  path text NOT NULL,
  name varchar(255),
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS gallery_items_album_idx ON public.gallery_items (gallery_album_id);

CREATE TABLE IF NOT EXISTS public.wilayah_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id bigint NOT NULL UNIQUE REFERENCES public.websites(id) ON DELETE CASCADE,
  banner_title varchar(255),
  banner_subtitle varchar(255),
  judul_profil varchar(255),
  luas_wilayah varchar(100),
  jumlah_rw varchar(50),
  jumlah_rt varchar(50),
  jumlah_kk varchar(50),
  total_jiwa varchar(50),
  kepuasan_warga varchar(50),
  batas_utara varchar(255),
  batas_timur varchar(255),
  batas_selatan varchar(255),
  batas_barat varchar(255),
  quote_profil text,
  maps_embed_url text,
  contact_address text,
  operating_hours text,
  office_phone varchar(100),
  whatsapp_phone varchar(100),
  official_email varchar(255),
  google_maps_url text,
  instagram_username varchar(255),
  facebook_page_name varchar(255),
  youtube_channel_url text,
  visi text,
  misi text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  website_id bigint REFERENCES public.websites(id) ON DELETE SET NULL,
  action varchar(255) NOT NULL,
  description text,
  properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip_address varchar(45),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activity_logs_created_idx
  ON public.activity_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS activity_logs_user_created_idx
  ON public.activity_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS activity_logs_website_created_idx
  ON public.activity_logs (website_id, created_at DESC);

-- Seed idempoten: aman dijalankan ulang pada project kosong yang sama.
INSERT INTO public.templates (name, slug, description, is_active)
VALUES
  ('Template Dinas', 'dinas', 'Template untuk website Dinas Pemerintah', true),
  ('Template Kecamatan', 'kecamatan', 'Template untuk website Kecamatan dengan statistik wilayah', true),
  ('Template Kelurahan', 'kelurahan', 'Template untuk website Kelurahan dengan profil masyarakat', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.menu_items (name, slug, "order", available_for)
VALUES
  ('Beranda', 'beranda', 1, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Profil', 'profil', 2, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Visi dan Misi', 'visi-dan-misi', 3, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Program dan Kegiatan', 'program-dan-kegiatan', 4, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Struktur Organisasi', 'struktur-organisasi', 5, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Profil Pimpinan', 'profil-pimpinan', 6, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('PPID', 'ppid', 7, ARRAY['dinas', 'kecamatan']),
  ('Daftar Informasi Publik', 'daftar-informasi-publik', 8, ARRAY['dinas', 'kecamatan']),
  ('Daftar Informasi Dikecualikan', 'daftar-informasi-dikecualikan', 9, ARRAY['dinas', 'kecamatan']),
  ('Informasi Wajib Berkala', 'informasi-wajib-berkala', 10, ARRAY['dinas', 'kecamatan']),
  ('Informasi Tersedia Setiap Saat', 'informasi-tersedia-setiap-saat', 11, ARRAY['dinas', 'kecamatan']),
  ('Informasi Serta Merta', 'informasi-serta-merta', 12, ARRAY['dinas', 'kecamatan']),
  ('Permohonan Informasi Online', 'permohonan-informasi-online', 13, ARRAY['dinas', 'kecamatan']),
  ('Pengajuan Keberatan Online', 'pengajuan-keberatan-online', 14, ARRAY['dinas', 'kecamatan']),
  ('PPID Utama', 'ppid-utama', 15, ARRAY['dinas', 'kecamatan']),
  ('Berita', 'berita', 16, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Foto', 'galeri-gambar', 17, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Video', 'galeri-video', 18, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Informasi', 'informasi', 19, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Pengumuman', 'pengumuman', 20, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Inovasi', 'inovasi', 21, ARRAY['kecamatan', 'kelurahan']),
  ('Agenda Kegiatan', 'agenda-kegiatan', 22, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Layanan', 'layanan', 23, ARRAY['dinas', 'kecamatan', 'kelurahan']),
  ('Kontak', 'kontak', 24, ARRAY['dinas', 'kecamatan', 'kelurahan'])
ON CONFLICT (slug) DO NOTHING;

-- Tidak ada policy RLS publik: Supabase Data API (anon/authenticated) tidak dapat
-- membaca atau mengubah baris. Aplikasi mengakses DB hanya dari server Next.js.
-- Jangan menambahkan service key / password database ke bundle browser.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.websites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.innovations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wilayah_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Catatan kompatibilitas:
-- 1. Skrip asli memodelkan profiles/auth.users (Supabase Auth); proyek Next.js saat
--    ini memakai public.users + bcrypt/JWT. Skrip ini sengaja mengikuti kode aplikasi.
-- 2. Rute konten tertentu mungkin memerlukan penyesuaian skema setelah implementasi
--    lengkap diverifikasi. gallery_items memakai gallery_album_id.
-- 3. Buat akun super-admin melalui alur admin/seed aman. Jangan menyimpan password
--    teks biasa atau menambahkan akun default dengan password yang diketahui umum.
