-- ==============================================================================
-- SKRIP DATABASE SUPABASE - MULTISITE DISKOMINFO
-- ==============================================================================
-- Petunjuk:
-- Salin seluruh isi skrip ini ke SQL Editor di Dashboard Supabase Anda,
-- lalu klik RUN.
-- ==============================================================================

-- 1. EXTENSIONS & TIPE DATA (ENUM)
create extension if not exists "uuid-ossp";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'website_status') then
    create type website_status as enum ('active', 'inactive', 'suspended');
  end if;
  if not exists (select 1 from pg_type where typname = 'gallery_album_type') then
    create type gallery_album_type as enum ('image', 'video');
  end if;
  if not exists (select 1 from pg_type where typname = 'gallery_item_type') then
    create type gallery_item_type as enum ('image', 'video', 'youtube');
  end if;
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type user_role as enum ('super-admin', 'admin-dinas', 'admin-kecamatan', 'admin-kelurahan');
  end if;
end $$;

-- 2. TABEL PROFILES (Terhubung dengan Supabase auth.users)
create table if not exists public.profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    role user_role default 'admin-kelurahan',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    deleted_at timestamp with time zone
);

-- 3. TABEL TEMPLATES
create table if not exists public.templates (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255) not null unique,
    description text,
    preview_image varchar(255),
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TABEL WEBSITES
create table if not exists public.websites (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete cascade not null,
    name varchar(255) not null,
    description text,
    subdomain varchar(255) not null unique,
    domain varchar(255),
    template_id bigint references public.templates(id) on delete set null,
    status website_status default 'active',
    settings jsonb default '{}'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    deleted_at timestamp with time zone
);

-- 5. TABEL MENU ITEMS
create table if not exists public.menu_items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255) not null,
    "order" integer default 0,
    available_for text[] not null, -- ['dinas', 'kecamatan', 'kelurahan']
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. TABEL CONTENTS
create table if not exists public.contents (
    id bigint generated by default as identity primary key,
    website_id bigint references public.websites(id) on delete cascade not null,
    menu_item_id bigint references public.menu_items(id) on delete cascade not null,
    title varchar(255),
    body text,
    images jsonb default '[]'::jsonb,
    files jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(website_id, menu_item_id)
);

-- 7. TABEL NEWS ITEMS (Link Berita & Preview)
create table if not exists public.news_items (
    id bigint generated by default as identity primary key,
    website_id bigint references public.websites(id) on delete cascade not null,
    url varchar(1000) not null,
    title varchar(500),
    image varchar(1000),
    excerpt text,
    source_domain varchar(255),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_news_items_website on public.news_items (website_id, created_at desc);

-- 8. TABEL GALLERY ALBUMS & GALLERY ITEMS
create table if not exists public.gallery_albums (
    id bigint generated by default as identity primary key,
    website_id bigint references public.websites(id) on delete cascade not null,
    type gallery_album_type not null,
    title varchar(255) not null,
    album_date date,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_gallery_albums_website_type on public.gallery_albums (website_id, type);

create table if not exists public.gallery_items (
    id bigint generated by default as identity primary key,
    gallery_album_id bigint references public.gallery_albums(id) on delete cascade not null,
    type gallery_item_type not null,
    path text not null,
    name varchar(255),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. TABEL WILAYAH PROFILES (Kecamatan & Kelurahan Statistik)
create table if not exists public.wilayah_profiles (
    id bigint generated by default as identity primary key,
    website_id bigint references public.websites(id) on delete cascade not null unique,
    banner_title varchar(255),
    banner_subtitle varchar(255),
    judul_profil varchar(255),
    luas_wilayah varchar(100),
    jumlah_rw varchar(50),
    jumlah_rt varchar(50),
    jumlah_kk varchar(50),
    total_jiwa varchar(50),
    kepuasan_warga varchar(50),
    batas_utara varchar(255),
    batas_timur varchar(255),
    batas_selatan varchar(255),
    batas_barat varchar(255),
    quote_profil text,
    maps_embed_url text,
    visi text,
    misi text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. TABEL ACTIVITY LOGS
create table if not exists public.activity_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    website_id bigint references public.websites(id) on delete set null,
    action varchar(255) not null,
    description text,
    properties jsonb default '{}'::jsonb,
    ip_address varchar(45),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 11. TRIGGER AUTO-CREATE PROFILE SAAT USER REGISTER DI AUTH.USERS
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce((new.raw_user_meta_data->>'role')::user_role, 'admin-kelurahan')
  )
  on conflict (id) do update
  set email = excluded.email,
      name = coalesce(excluded.name, public.profiles.name);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update on auth.users
  for each row execute procedure public.handle_new_user();

-- 12. INITIAL SEED DATA (TEMPLATES & MENU ITEMS)
insert into public.templates (name, slug, description, is_active) values
('Template Dinas', 'dinas', 'Template untuk website Dinas Pemerintah', true),
('Template Kecamatan', 'kecamatan', 'Template untuk website Kecamatan dengan statistik wilayah', true),
('Template Kelurahan', 'kelurahan', 'Template untuk website Kelurahan dengan profil masyarakat', true)
on conflict (slug) do nothing;

insert into public.menu_items (name, slug, "order", available_for) values
('Beranda', 'beranda', 1, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Profil', 'profil', 2, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Visi dan Misi', 'visi-dan-misi', 3, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Program dan Kegiatan', 'program-dan-kegiatan', 4, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Struktur Organisasi', 'struktur-organisasi', 5, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Profil Pimpinan', 'profil-pimpinan', 6, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('PPID', 'ppid', 7, ARRAY['dinas', 'kecamatan']),
('Daftar Informasi Publik', 'daftar-informasi-publik', 8, ARRAY['dinas', 'kecamatan']),
('Daftar Informasi Dikecualikan', 'daftar-informasi-dikecualikan', 9, ARRAY['dinas', 'kecamatan']),
('Informasi Wajib Berkala', 'informasi-wajib-berkala', 10, ARRAY['dinas', 'kecamatan']),
('Informasi Tersedia Setiap Saat', 'informasi-tersedia-setiap-saat', 11, ARRAY['dinas', 'kecamatan']),
('Informasi Serta Merta', 'informasi-serta-merta', 12, ARRAY['dinas', 'kecamatan']),
('Permohonan Informasi Online', 'permohonan-informasi-online', 13, ARRAY['dinas', 'kecamatan']),
('Pengajuan Keberatan Online', 'pengajuan-keberatan-online', 14, ARRAY['dinas', 'kecamatan']),
('PPID Utama', 'ppid-utama', 15, ARRAY['dinas', 'kecamatan']),
('Berita', 'berita', 16, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Foto', 'galeri-gambar', 17, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Video', 'galeri-video', 18, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Informasi', 'informasi', 19, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Pengumuman', 'pengumuman', 20, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Inovasi', 'inovasi', 21, ARRAY['kecamatan', 'kelurahan']),
('Agenda Kegiatan', 'agenda-kegiatan', 22, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Layanan', 'layanan', 23, ARRAY['dinas', 'kecamatan', 'kelurahan']),
('Kontak', 'kontak', 24, ARRAY['dinas', 'kecamatan', 'kelurahan'])
on conflict do nothing;

-- 13. ROW LEVEL SECURITY (RLS) DASAR (Bisa diakses publik untuk read website aktif)
alter table public.templates enable row level security;
alter table public.websites enable row level security;
alter table public.menu_items enable row level security;
alter table public.contents enable row level security;
alter table public.news_items enable row level security;
alter table public.gallery_albums enable row level security;
alter table public.gallery_items enable row level security;
alter table public.wilayah_profiles enable row level security;

-- Policy: Publik boleh membaca website yang statusnya active
create policy "Allow public read active websites" on public.websites for select using (status = 'active');
create policy "Allow public read templates" on public.templates for select using (true);
create policy "Allow public read menu_items" on public.menu_items for select using (is_active = true);
create policy "Allow public read contents" on public.contents for select using (true);
create policy "Allow public read news_items" on public.news_items for select using (true);
create policy "Allow public read gallery_albums" on public.gallery_albums for select using (true);
create policy "Allow public read gallery_items" on public.gallery_items for select using (true);
create policy "Allow public read wilayah_profiles" on public.wilayah_profiles for select using (true);

-- Policy untuk authenticated users (Admin / User Login)
create policy "Allow authenticated full access to websites" on public.websites for all using (auth.role() = 'authenticated');
create policy "Allow authenticated full access to contents" on public.contents for all using (auth.role() = 'authenticated');
create policy "Allow authenticated full access to news_items" on public.news_items for all using (auth.role() = 'authenticated');
create policy "Allow authenticated full access to gallery_albums" on public.gallery_albums for all using (auth.role() = 'authenticated');
create policy "Allow authenticated full access to gallery_items" on public.gallery_items for all using (auth.role() = 'authenticated');
create policy "Allow authenticated full access to wilayah_profiles" on public.wilayah_profiles for all using (auth.role() = 'authenticated');
create policy "Allow authenticated full access to profiles" on public.profiles for all using (auth.role() = 'authenticated');
create policy "Allow public read profiles" on public.profiles for select using (true);
