// ─── DEFINISI 23 MODUL KONTEN PORTAL MULTI-TENANT KOTA BANDUNG ───────────────

export const CONTENT_MODULES = [
  // ─── 1. Halaman Utama & Profil (7 Modul) ────────────────────────────────────
  {
    slug: 'beranda',
    title: 'Beranda',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Edit',
    iconName: 'home',
    iconBg: 'bg-blue-100/70 text-blue-700',
    description: 'Konfigurasi slider hero, sambutan pimpinan, dan tautan layanan cepat di beranda.',
  },
  {
    slug: 'profil',
    title: 'Profil',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Edit',
    iconName: 'description',
    iconBg: 'bg-teal-100/70 text-teal-700',
    description: 'Visi, misi, sejarah singkat, dan tugas pokok serta fungsi perangkat daerah.',
  },
  {
    slug: 'program-dan-kegiatan',
    title: 'Program dan Kegiatan',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Edit',
    iconName: 'assignment',
    iconBg: 'bg-amber-100/70 text-amber-700',
    description: 'Rencana kerja strategis, program prioritas kewilayahan, dan target kinerja tahunan.',
  },
  {
    slug: 'struktur-organisasi',
    title: 'Struktur Organisasi',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Kelola',
    iconName: 'account_tree',
    iconBg: 'bg-blue-100/70 text-blue-700',
    description: 'Bagan hierarki kepegawaian, seksi/bidang, dan susunan pejabat struktural.',
  },
  {
    slug: 'profil-pimpinan',
    title: 'Profil Pimpinan',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Kelola',
    iconName: 'badge',
    iconBg: 'bg-indigo-100/70 text-indigo-700',
    description: 'Foto pimpinan, riwayat karir, dan sambutan resmi Kepala Perangkat Daerah / Camat.',
  },
  {
    slug: 'layanan',
    title: 'Layanan',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Kelola',
    iconName: 'room_service',
    iconBg: 'bg-purple-100/70 text-purple-700',
    description: 'Daftar prosedur standar pelayanan, syarat administrasi, dan link layanan publik.',
  },
  {
    slug: 'kontak',
    title: 'Kontak',
    category: 'utama',
    categoryLabel: 'Halaman Utama & Profil',
    actionType: 'Edit',
    iconName: 'contact_phone',
    iconBg: 'bg-rose-100/70 text-rose-700',
    description: 'Alamat kantor, nomor telepon pelayanan, email resmi, dan peta lokasi kantor.',
  },

  // ─── 2. Informasi Publik & PPID (10 Modul) ──────────────────────────────────
  {
    slug: 'ppid',
    title: 'PPID',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Edit',
    iconName: 'verified_user',
    iconBg: 'bg-blue-100/70 text-blue-700',
    description: 'Profil PPID Pelaksana, struktur pengelola, dan komitmen keterbukaan informasi.',
  },
  {
    slug: 'ppid-utama',
    title: 'PPID Utama',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'security',
    iconBg: 'bg-indigo-100/70 text-indigo-700',
    description: 'Integrasi dan sinkronisasi ke portal PPID Utama Kota Bandung (ppid.bandung.go.id).',
  },
  {
    slug: 'daftar-informasi-publik',
    title: 'Daftar Informasi Publik',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Edit',
    iconName: 'table_chart',
    iconBg: 'bg-cyan-100/70 text-cyan-700',
    description: 'Tabel ringkasan Daftar Informasi Publik (DIP) resmi yang dapat diakses masyarakat.',
  },
  {
    slug: 'daftar-informasi-dikecualikan',
    title: 'Daftar Informasi Dikecualikan',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'lock',
    iconBg: 'bg-red-100/70 text-red-700',
    description: 'Surat ketetapan dan dokumen uji konsekuensi informasi yang dikecualikan.',
  },
  {
    slug: 'informasi-wajib-berkala',
    title: 'Informasi Wajib Berkala',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'calendar_month',
    iconBg: 'bg-sky-100/70 text-sky-700',
    description: 'Laporan keuangan, RKA/DPA, LAKIP, dan dokumen evaluasi berkala.',
  },
  {
    slug: 'informasi-tersedia-setiap-saat',
    title: 'Informasi Tersedia Setiap Saat',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'schedule',
    iconBg: 'bg-teal-100/70 text-teal-700',
    description: 'Daftar regulasi, SOP internal, perjanjian kerjasama, dan data aset daerah.',
  },
  {
    slug: 'informasi-serta-merta',
    title: 'Informasi Serta Merta',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'warning',
    iconBg: 'bg-amber-100/70 text-amber-700',
    description: 'Pemberitahuan darurat, mitigasi bencana, dan informasi keselamatan publik.',
  },
  {
    slug: 'permohonan-informasi-online',
    title: 'Permohonan Informasi Online',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'inbox',
    iconBg: 'bg-emerald-100/70 text-emerald-700',
    description: 'Formulir daring dan rekap permohonan informasi publik dari pemohon.',
  },
  {
    slug: 'pengajuan-keberatan-online',
    title: 'Pengajuan Keberatan Online',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'report_problem',
    iconBg: 'bg-orange-100/70 text-orange-700',
    description: 'Layanan daring penyampaian keberatan atas permohonan informasi ke atasan PPID.',
  },
  {
    slug: 'inovasi',
    title: 'Inovasi',
    category: 'ppid',
    categoryLabel: 'Informasi Publik & PPID',
    actionType: 'Kelola',
    iconName: 'lightbulb',
    iconBg: 'bg-violet-100/70 text-violet-700',
    description: 'Publikasi karya inovasi pelayanan publik dan digitalisasi tata kelola OPD.',
  },

  // ─── 3. Berita & Media (6 Modul) ─────────────────────────────────────────────
  {
    slug: 'berita',
    title: 'Berita',
    category: 'berita',
    categoryLabel: 'Berita & Media',
    actionType: 'Kelola',
    iconName: 'newspaper',
    iconBg: 'bg-blue-100/70 text-blue-700',
    description: 'Artikel rilis berita, siaran pers, dan liputan kegiatan resmi perangkat daerah.',
  },
  {
    slug: 'galeri-gambar',
    title: 'Galeri Gambar',
    category: 'berita',
    categoryLabel: 'Berita & Media',
    actionType: 'Kelola',
    iconName: 'collections',
    iconBg: 'bg-fuchsia-100/70 text-fuchsia-700',
    description: 'Album foto dokumentasi kegiatan, peresmian, dan arsip visual kegiatan.',
  },
  {
    slug: 'galeri-video',
    title: 'Galeri Video',
    category: 'berita',
    categoryLabel: 'Berita & Media',
    actionType: 'Kelola',
    iconName: 'video_library',
    iconBg: 'bg-red-100/70 text-red-700',
    description: 'Dokumentasi video publikasi, rekaman acara, dan integrasi video YouTube.',
  },
  {
    slug: 'informasi',
    title: 'Informasi',
    category: 'berita',
    categoryLabel: 'Berita & Media',
    actionType: 'Kelola',
    iconName: 'info',
    iconBg: 'bg-cyan-100/70 text-cyan-700',
    description: 'Infografis edukatif, data statistik tematik, dan publikasi umum masyarakat.',
  },
  {
    slug: 'pengumuman',
    title: 'Pengumuman',
    category: 'berita',
    categoryLabel: 'Berita & Media',
    actionType: 'Kelola',
    iconName: 'campaign',
    iconBg: 'bg-amber-100/70 text-amber-700',
    description: 'Surat edaran, pengumuman kedinasan, dan himbauan penting kepada masyarakat.',
  },
  {
    slug: 'agenda-kegiatan',
    title: 'Agenda Kegiatan',
    category: 'berita',
    categoryLabel: 'Berita & Media',
    actionType: 'Kelola',
    iconName: 'event',
    iconBg: 'bg-emerald-100/70 text-emerald-700',
    description: 'Jadwal agenda pimpinan, musrenbang, dan kegiatan kemasyarakatan kewilayahan.',
  },
]
