// Master data instansi / OPD Pemerintah Kota Bandung

export const KELURAHAN_LIST = [
  'Campaka',
  'Ciroyom',
  'Dungus Cariang',
  'Garuda',
  'Kebon Jeruk',
  'Maleber',
  'Antapani Kidul',
  'Antapani Kulon',
  'Antapani Tengah',
  'Antapani Wetan',
  'Cisaranten Bina Harapan',
  'Cisaranten Endah',
  'Cisaranten Kulon',
  'Sukamiskin',
  'Cibadak',
  'Karanganyar',
  'Karasak',
  'Nyengseret',
  'Panjunan',
  'Pelindung Hewan',
  'Babakan',
  'Babakan Ciparay',
  'Cirangrang',
  'Margahayu Utara',
  'Margasuka',
  'Sukahaji',
  'Batununggal',
  'Kujangsari',
  'Mengger',
  'Wates',
  'Caringin',
  'Cibuntu',
  'Cigondewah Kaler',
  'Cigondewah Kidul',
  'Cigondewah Rahayu',
  'Cijerah',
  'Gempolsari',
  'Warung Muncang',
  'Cihapit',
  'Citarum',
  'Tamansari',
  'Binong',
  'Cibangkong',
  'Gumuruh',
  'Kacapiring',
  'Kebon Gedang',
  'Kebon Waru',
  'Maleer',
  'Samoja',
  'Babakan Asih',
  'Babakan Tarogong',
  'Jamika',
  'Kopo',
  'Suka Asih',
  'Cibaduyut',
  'Cibaduyut Kidul',
  'Cibaduyut Wetan',
  'Kebon Lega',
  'Mekarwangi',
  'Situsaeur',
  'Cijawura',
  'Jatisari',
  'Margasari',
  'Sekejati',
  'Cigadung',
  'Cihaur Geulis',
  'Neglasari',
  'Sukaluyu',
  'Cicadas',
  'Cikutra',
  'Padasuka',
  'Pasirlayung',
  'Sukamaju',
  'Sukapada',
  'Cipadung',
  'Cisurupan',
  'Palasari',
  'Pasirbiru',
  'Arjuna',
  'Husein Sastranegara',
  'Jatiyuwono',
  'Pajajaran',
  'Pamoyanan',
  'Pasirkaliki',
  'Ciumbuleuit',
  'Hegarmanah',
  'Ledeng',
  'Babakan Penghulu',
  'Cisaranten Wetan',
  'Dago',
  'Lebak Siliwangi',
  'Lebakgede',
  'Sadangserang',
  'Sekeloa',
  'Cipaganti',
  'Cimincrang',
  'Cisaranten Kidul',
  'Rancabolang',
  'Rancanumpang',
  'Babakan Surabaya',
  'Babakan Sari',
  'Cicaheum',
  'Compreng',
  'Kebon Jayanti',
  'Kebon Kangkung',
  'Sukapura',
  'Burangrang',
  'Cijagra',
  'Cikawao',
  'Lingkar Selatan',
  'Malabar',
  'Paledang',
  'Turangga',
  'Jatihandap',
  'Karang Pamulang',
  'Pasir Impun',
  'Sindangjaya',
  'Cipadung Kidul',
  'Cipadung Kulon',
  'Cipadung Wetan',
  'Mekarmulya',
  'Cipamokolan',
  'Derwati',
  'Manjahlega',
  'Mekar Jaya',
  'Ancol',
  'Balonggede',
  'Ciateul',
  'Cigereleng',
  'Ciseureuh',
  'Pasirluyu',
  'Pungkur',
  'Cipedes',
  'Pasteur',
  'Sukagalih',
  'Sukajadi',
  'Sukawarna',
  'Gegerkalong',
  'Isola',
  'Sarijadi',
  'Sukarasa',
  'Babakan Ciamis',
  'Braga',
  'Kebon Pisang',
  'Merdeka',
  'Cigending',
  'Pasir Endah',
  'Pasir Jati',
  'Pasirwangi',
  'Pasirjati',
  'Ujungberung',
]

export const KECAMATAN_LIST = [
  'Andir',
  'Antapani',
  'Arcamanik',
  'Astana Anyar',
  'Babakan Ciparay',
  'Bandung Kidul',
  'Bandung Kulon',
  'Bandung Wetan',
  'Batununggal',
  'Bojongloa Kaler',
  'Bojongloa Kidul',
  'Buahbatu',
  'Cibeunying Kaler',
  'Cibeunying Kidul',
  'Cibiru',
  'Cicendo',
  'Cidadap',
  'Cinambo',
  'Coblong',
  'Gedebage',
  'Kiaracondong',
  'Lengkong',
  'Mandalajati',
  'Panyileukan',
  'Rancasari',
  'Regol',
  'Sukajadi',
  'Sukasari',
  'Sumur Bandung',
  'Ujungberung',
]

export const DINAS_LIST = [
  'Dinas Pendidikan',
  'Dinas Kesehatan',
  'Dinas Sumber Daya Air dan Bina Marga',
  'Dinas Perumahan dan Kawasan Permukiman',
  'Dinas Kebakaran dan Penanggulangan Bencana',
  'Dinas Sosial',
  'Dinas Tenaga Kerja',
  'Dinas Ketahanan Pangan dan Pertanian',
  'Dinas Lingkungan Hidup',
  'Dinas Kependudukan dan Pencatatan Sipil',
  'Dinas Pengendalian Penduduk dan Keluarga Berencana',
  'Dinas Perhubungan',
  'Dinas Komunikasi dan Informatika',
  'Dinas Koperasi dan Usaha Mikro Kecil dan Menengah',
  'Dinas Perdagangan dan Perindustrian',
  'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
  'Dinas Pemuda dan Olahraga',
  'Dinas Kebudayaan dan Pariwisata',
  'Dinas Perpustakaan dan Kearsipan',
]

export function getInstansiOptionsByRole(role) {
  if (role === 'admin-dinas') {
    return DINAS_LIST.map((item) => ({
      value: item,
      title: item,
      category: 'Dinas / OPD',
    }))
  }

  if (role === 'admin-kecamatan') {
    return KECAMATAN_LIST.map((item) => ({
      value: `Kecamatan ${item}`,
      title: `Kecamatan ${item}`,
      category: 'Kecamatan',
    }))
  }

  if (role === 'admin-kelurahan') {
    return KELURAHAN_LIST.map((item) => ({
      value: `Kelurahan ${item}`,
      title: `Kelurahan ${item}`,
      category: 'Kelurahan',
    }))
  }

  // Super admin atau fallback: tampilkan semua
  return [
    { value: 'Diskominfo Kota Bandung', title: 'Diskominfo Kota Bandung', category: 'Pemerintah Kota' },
    { value: 'Sekretariat Daerah Kota Bandung', title: 'Sekretariat Daerah Kota Bandung', category: 'Pemerintah Kota' },
    ...DINAS_LIST.map((item) => ({ value: item, title: item, category: 'Dinas / OPD' })),
    ...KECAMATAN_LIST.map((item) => ({ value: `Kecamatan ${item}`, title: `Kecamatan ${item}`, category: 'Kecamatan' })),
    ...KELURAHAN_LIST.map((item) => ({ value: `Kelurahan ${item}`, title: `Kelurahan ${item}`, category: 'Kelurahan' })),
  ]
}

export const PERMISSION_LIST = [
  { id: 'manage-all-websites', label: 'Kelola Semua Website' },
  { id: 'manage-users', label: 'Kelola Akun Pengguna' },
  { id: 'manage-assigned-website', label: 'Kelola Website OPD Terhubung' },
  { id: 'manage-templates', label: 'Kelola Template Website' },
  { id: 'view-all-logs', label: 'Lihat Semua Audit Logs' },
  { id: 'view-own-logs', label: 'Lihat Log Aktivitas Sendiri' },
]

export function getDefaultPermissionsByRole(role) {
  if (role === 'super-admin') {
    return ['manage-all-websites', 'manage-templates', 'manage-users', 'view-all-logs']
  }
  return ['manage-assigned-website', 'view-own-logs']
}
