import Link from 'next/link'
import { ArrowRight, CalendarDays, Clock3, FileText, Image as ImageIcon, MapPin, Play } from 'lucide-react'
import { plainContent } from '@/lib/public-kecamatan'
import { PortalFooter, PortalHeader } from './PortalChrome'
import HeroSlider from './HeroSlider'

function SectionTitle({ eyebrow, title, href, linkLabel = 'Lihat selengkapnya' }) {
  return <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><span className="inline-flex rounded-md bg-teal-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.15em] text-teal-700">{eyebrow}</span><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-900 sm:text-2xl">{title}</h2></div>{href && <Link href={href} className="inline-flex items-center gap-1 text-xs font-bold text-teal-700 hover:text-teal-900">{linkLabel}<ArrowRight className="h-3.5 w-3.5"/></Link>}</div>
}

function EmptySafeText({ value, className = '' }) {
  const text = plainContent(value || '')
  return text ? <p className={`whitespace-pre-line ${className}`}>{text}</p> : null
}

function PublicModuleCards({ portal }) {
  const iconBySlug = {
    profil: '◉', beranda: '⌂', 'program-dan-kegiatan': '▤', 'struktur-organisasi': '♧', 'profil-pimpinan': '☆', layanan: '◇', kontak: '⌖', ppid: '◈', 'ppid-utama': '◉', 'daftar-informasi-publik': '▦', 'daftar-informasi-dikecualikan': '▣', 'informasi-wajib-berkala': '▤', 'informasi-tersedia-setiap-saat': '◷', 'informasi-serta-merta': '△', 'permohonan-informasi-online': '↗', 'pengajuan-keberatan-online': '!', inovasi: '✳', berita: '▧', 'galeri-gambar': '▧', 'galeri-video': '▷', informasi: 'ⓘ', pengumuman: '♧', 'agenda-kegiatan': '▣',
  }
  const descriptions = {
    profil: 'Gambaran umum dan data wilayah', 'program-dan-kegiatan': 'Program dan kegiatan instansi', 'struktur-organisasi': 'Bagan tata kelola dan hierarki', 'profil-pimpinan': 'Informasi pimpinan kecamatan', layanan: 'Layanan dan persyaratan publik', kontak: 'Alamat, peta, dan kanal kontak', ppid: 'Permohonan informasi dan transparansi', 'ppid-utama': 'Integrasi informasi PPID', 'daftar-informasi-publik': 'Dokumen informasi yang tersedia', 'daftar-informasi-dikecualikan': 'Informasi yang dikecualikan', 'informasi-wajib-berkala': 'Publikasi informasi berkala', 'informasi-tersedia-setiap-saat': 'Dokumen yang tersedia setiap saat', 'informasi-serta-merta': 'Informasi serta-merta', 'permohonan-informasi-online': 'Tata cara permohonan informasi', 'pengajuan-keberatan-online': 'Prosedur pengajuan keberatan', inovasi: 'Inovasi program dan pelayanan', berita: 'Berita dan publikasi terbaru', 'galeri-gambar': 'Dokumentasi foto kegiatan', 'galeri-video': 'Video publikasi dan dokumentasi', informasi: 'Informasi umum kecamatan', pengumuman: 'Surat edaran dan pengumuman', 'agenda-kegiatan': 'Jadwal kegiatan kewilayahan',
  }
  const base = `/${portal.website.subdomain}`
  return <section id="arsip" className="bg-slate-50 px-5 py-14 sm:py-16 lg:px-10"><div className="mx-auto w-full max-w-[1440px]"><SectionTitle eyebrow="Navigasi Portal" title="Arsip & Modul Dokumen Resmi"/><p className="-mt-3 mb-7 max-w-2xl text-sm text-slate-500">Akses cepat ke informasi, layanan, dokumentasi, dan dokumen resmi kecamatan.</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{portal.modules.map((module) => <Link key={module.slug} href={`${base}/${module.slug}`} className="group flex min-h-32 flex-col rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-md"><span className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl bg-teal-50 text-base font-bold text-teal-700">{iconBySlug[module.slug] || '•'}</span><span className="text-xs font-bold leading-snug text-slate-800 group-hover:text-teal-800">{module.title}</span><span className="mt-1 line-clamp-2 text-[11px] leading-relaxed text-slate-500">{descriptions[module.slug] || module.description}</span><span className="mt-auto pt-3 text-[10px] font-extrabold text-teal-700">Akses menu →</span></Link>)}</div></div></section>
}

export default function PublicKecamatanHome({ portal }) {
  const { website, profile, contents, news, announcements, agendas, services, innovations, albums, heroSlides = [] } = portal
  const base = `/${website.subdomain}`
  const homeContent = contents.beranda
  const profileContent = contents.profil
  const introductionTitle = homeContent?.title?.trim()
  const introductionBody = plainContent(homeContent?.body)
  const hasIntroduction = Boolean(introductionTitle || introductionBody)
  const profileFallback = profileContent?.body && profileContent.body !== 'Konten profil wilayah' ? profileContent.body : ''
  const profileSummary = plainContent(profile?.visi || profileFallback)
  const latestNews = news.slice(0, 3)
  const upcomingAgenda = agendas.filter((item) => new Date(item.end_date || item.start_date) >= new Date(new Date().toDateString())).slice(0, 3)
  const stats = [
    ['Luas Wilayah', profile?.luas_wilayah, 'km²'], ['Rukun Warga', profile?.jumlah_rw, 'RW'], ['Rukun Tetangga', profile?.jumlah_rt, 'RT'], ['Total Penduduk', profile?.total_jiwa, 'Jiwa'],
  ].filter(([, value]) => value !== null && value !== undefined && String(value).trim() !== '')
  const hasProfile = Boolean(profileSummary || profile?.misi || stats.length)

  return <div className="public-portal min-h-screen bg-white text-slate-900"><PortalHeader website={website} profile={profile}/>
    {heroSlides.length > 0 && <HeroSlider slides={heroSlides} website={website} base={base}/>}

    {hasIntroduction && <section className="border-b border-slate-100 bg-white px-5 py-10 text-center sm:py-12 lg:px-10"><div className="mx-auto max-w-3xl"><span className="inline-flex rounded-md bg-teal-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.15em] text-teal-700">Integritas & Transparansi</span>{introductionTitle && <h2 className="mt-3 text-xl font-extrabold tracking-tight text-slate-900 sm:text-2xl">{introductionTitle}</h2>}{introductionBody && <p className="mx-auto mt-3 whitespace-pre-line text-sm leading-relaxed text-slate-600">{introductionBody}</p>}</div></section>}

    {services.length > 0 && <section className="px-5 py-12 sm:py-14 lg:px-10"><div className="mx-auto w-full max-w-[1440px]"><div className="mx-auto mb-8 max-w-2xl text-center"><span className="rounded-md bg-teal-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.15em] text-teal-700">Layanan Prioritas Warga</span><h2 className="mt-3 text-xl font-extrabold sm:text-2xl">Akses Cepat Pengurusan Dokumen & Pengaduan</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.slice(0, 6).map((service, index) => <article key={service.id} className={`flex flex-col rounded-2xl border border-slate-200 border-t-[3px] bg-white p-5 shadow-sm ${['border-t-teal-500','border-t-amber-500','border-t-blue-500'][index % 3]}`}><span className="text-[10px] font-extrabold uppercase tracking-wide text-teal-700">{service.category || 'Layanan Publik'}</span><h3 className="mt-2 font-bold">{service.name}</h3><EmptySafeText value={service.description} className="mt-2 line-clamp-3 text-xs leading-relaxed text-slate-500"/>{service.requirements && <p className="mt-2 line-clamp-2 text-[11px] text-slate-500">Persyaratan: {plainContent(service.requirements)}</p>}<Link href={`${base}/layanan`} className="mt-auto inline-flex items-center gap-1 border-t border-slate-100 pt-4 mt-4 text-[11px] font-extrabold text-teal-700">{service.application_url ? 'Mulai layanan' : 'Lihat detail layanan'}<ArrowRight className="h-3.5 w-3.5"/></Link></article>)}</div></div></section>}

    {hasProfile && <section className="border-y border-slate-100 bg-slate-50 px-5 py-12 sm:py-16 lg:px-10"><div className="mx-auto w-full max-w-[1440px]"><div className="mb-6 text-center"><span className="rounded-md bg-teal-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.15em] text-teal-700">Data & Wilayah</span><h2 className="mt-3 text-2xl font-extrabold">Profil {website.name}</h2><p className="mt-2 text-xs text-slate-500">Gambaran umum letak administratif, potensi kewilayahan, serta operasional aparatur.</p></div><div className="grid gap-4 lg:grid-cols-[1.6fr_0.9fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Tentang {website.name}</h3><EmptySafeText value={profileSummary} className="mt-3 text-xs leading-relaxed text-slate-600"/>{profile?.misi && <div className="mt-3 border-t border-slate-100 pt-3"><h4 className="text-xs font-bold">Misi Wilayah</h4><EmptySafeText value={profile.misi} className="mt-1 text-xs leading-relaxed text-slate-600"/></div>}{stats.length > 0 && <div className="mt-5 grid grid-cols-2 gap-2 border-t border-slate-100 pt-4 sm:grid-cols-4">{stats.map(([label, value, unit]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><span className="block text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</span><strong className="mt-1 block text-lg font-black text-teal-700">{value} <small className="text-[10px] font-semibold">{unit}</small></strong></div>)}</div>}</article>{(profile?.contact_address || profile?.operating_hours || profile?.office_phone || profile?.official_email) && <aside className="rounded-2xl bg-[#071923] p-6 text-white"><span className="rounded bg-teal-800 px-2 py-1 text-[9px] font-extrabold uppercase tracking-wide text-teal-200">Aparatur Kewilayahan</span><h3 className="mt-3 font-bold">Kantor {website.name}</h3>{profile.contact_address && <p className="mt-2 text-xs leading-relaxed text-slate-300">{profile.contact_address}</p>}<dl className="mt-5 space-y-3 border-t border-white/10 pt-4 text-[11px]">{profile.operating_hours && <div className="flex justify-between gap-3"><dt className="text-slate-400">Jam Pelayanan</dt><dd className="text-right font-semibold text-teal-200">{profile.operating_hours}</dd></div>}{profile.office_phone && <div className="flex justify-between gap-3"><dt className="text-slate-400">Call Center</dt><dd className="text-right font-semibold">{profile.office_phone}</dd></div>}{profile.official_email && <div className="flex justify-between gap-3"><dt className="text-slate-400">Email Resmi</dt><dd className="break-all text-right font-semibold text-teal-200">{profile.official_email}</dd></div>}</dl></aside>}</div></div></section>}

    {(latestNews.length > 0 || upcomingAgenda.length > 0) && <section className="px-5 py-12 sm:py-16 lg:px-10"><div className="mx-auto w-full max-w-[1440px]">{latestNews.length > 0 && <div><SectionTitle eyebrow="Publikasi Terkini" title="Kabar & Berita Wilayah" href={`${base}/berita`}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{latestNews.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><a href={item.url} target="_blank" rel="noreferrer" className="block">{item.image ? <img src={item.image} alt="" className="h-44 w-full object-cover" loading="lazy" referrerPolicy="no-referrer"/> : <div className="flex h-44 items-center justify-center bg-gradient-to-br from-teal-900 to-blue-900 text-white"><FileText className="h-8 w-8 opacity-60"/></div>}<div className="p-5"><p className="text-[10px] font-semibold text-slate-400">{item.source_domain || 'Kabar Kecamatan'} · {new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(item.created_at))}</p><h3 className="mt-2 line-clamp-2 text-sm font-extrabold leading-snug">{item.title}</h3><p className="mt-2 line-clamp-3 text-xs leading-relaxed text-slate-500">{item.excerpt}</p><span className="mt-4 inline-flex items-center gap-1 text-[10px] font-extrabold text-teal-700">Baca selengkapnya<ArrowRight className="h-3 w-3"/></span></div></a></article>)}</div></div>}
      {upcomingAgenda.length > 0 && <div className={latestNews.length > 0 ? 'mt-12' : ''}><SectionTitle eyebrow="Agenda Kewilayahan" title="Agenda Kegiatan" href={`${base}/agenda-kegiatan`}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{upcomingAgenda.map((item) => <article key={item.id} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4"><span className="flex h-11 w-11 shrink-0 flex-col items-center justify-center rounded-xl bg-teal-50 text-teal-700"><CalendarDays className="h-4 w-4"/><span className="text-[9px] font-bold">{new Date(item.start_date).toLocaleDateString('id-ID',{day:'2-digit',month:'short'})}</span></span><div><h3 className="text-sm font-bold">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs text-slate-500">{plainContent(item.description)}</p>{item.time_range && <p className="mt-2 flex items-center gap-1 text-[10px] font-semibold text-teal-700"><Clock3 className="h-3 w-3"/>{item.time_range}</p>}{item.location && <p className="mt-1 flex items-center gap-1 text-[10px] text-slate-500"><MapPin className="h-3 w-3"/>{item.location}</p>}</div></article>)}</div></div>}
    </div></section>}

    {announcements.length > 0 && <section className="border-y border-amber-100 bg-amber-50/50 px-5 py-12 lg:px-10"><div className="mx-auto w-full max-w-[1440px]"><SectionTitle eyebrow="Informasi Resmi" title="Pengumuman Kecamatan" href={`${base}/pengumuman`}/><div className="grid gap-3 md:grid-cols-2">{announcements.slice(0,4).map((item) => <article key={item.id} className="rounded-xl border border-amber-100 bg-white p-4"><p className="text-[10px] font-semibold text-amber-700">Terbit {new Date(item.publish_date).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</p><h3 className="mt-1 font-bold">{item.title}</h3><p className="mt-2 line-clamp-3 whitespace-pre-line text-xs leading-relaxed text-slate-600">{plainContent(item.body)}</p>{item.attachment_path && <a href={item.attachment_path} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-teal-700"><FileText className="h-3.5 w-3.5"/>Unduh lampiran</a>}</article>)}</div></div></section>}

    {innovations.length > 0 && <section className="px-5 py-12 lg:px-10"><div className="mx-auto w-full max-w-[1440px]"><SectionTitle eyebrow="Gagasan & Layanan" title="Inovasi Wilayah" href={`${base}/inovasi`}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{innovations.slice(0,3).map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{item.cover_path && <img src={item.cover_path} alt="" className="h-40 w-full object-cover" loading="lazy"/>}<div className="p-5"><h3 className="font-bold">{item.title}</h3><p className="mt-2 line-clamp-3 text-xs leading-relaxed text-slate-500">{plainContent(item.description)}</p>{item.launch_year && <p className="mt-3 text-[10px] font-bold text-teal-700">Diluncurkan {item.launch_year}</p>}</div></article>)}</div></div></section>}

    {(albums.some((album) => album.type === 'image') || albums.some((album) => album.type === 'video')) && <section className="bg-slate-50 px-5 py-12 lg:px-10"><div className="mx-auto w-full max-w-[1440px] grid gap-10 xl:grid-cols-2">{['image','video'].map((type) => { const entries = albums.filter((album) => album.type === type); if (!entries.length) return null; const moduleSlug = type === 'image' ? 'galeri-gambar' : 'galeri-video'; return <div key={type}><SectionTitle eyebrow="Dokumentasi" title={type === 'image' ? 'Galeri Foto' : 'Galeri Video'} href={`${base}/${moduleSlug}`}/><div className="grid grid-cols-2 gap-3">{entries.slice(0,2).map((album) => <Link key={album.id} href={`${base}/${moduleSlug}`} className="overflow-hidden rounded-xl border border-slate-200 bg-white">{album.cover_path && type === 'image' ? <img src={album.cover_path} alt="" className="h-32 w-full object-cover" loading="lazy"/> : <div className="flex h-32 items-center justify-center bg-slate-900 text-white">{type === 'image' ? <ImageIcon className="h-7 w-7"/> : <Play className="h-7 w-7"/>}</div>}<div className="p-3"><p className="truncate text-xs font-bold">{album.title}</p><p className="mt-1 text-[10px] text-slate-500">{album.item_count} item</p></div></Link>)}</div></div> })}</div></section>}

    <PublicModuleCards portal={portal}/>
    <PortalFooter website={website} profile={profile}/>
  </div>
}
