-- Assign website accounts explicitly and persist the three fixed hero slots.
-- Safe to run more than once in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.website_user_access AS
SELECT u.id AS user_id, w.id AS website_id, u.id AS granted_by
FROM public.users u CROSS JOIN public.websites w
WITH NO DATA;

ALTER TABLE public.website_user_access
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'website_user_access_pk') THEN
    ALTER TABLE public.website_user_access ADD CONSTRAINT website_user_access_pk PRIMARY KEY (user_id, website_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'website_user_access_user_fk') THEN
    ALTER TABLE public.website_user_access ADD CONSTRAINT website_user_access_user_fk
      FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'website_user_access_website_fk') THEN
    ALTER TABLE public.website_user_access ADD CONSTRAINT website_user_access_website_fk
      FOREIGN KEY (website_id) REFERENCES public.websites(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'website_user_access_granted_by_fk') THEN
    ALTER TABLE public.website_user_access ADD CONSTRAINT website_user_access_granted_by_fk
      FOREIGN KEY (granted_by) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS website_user_access_website_idx ON public.website_user_access (website_id);
ALTER TABLE public.website_user_access ENABLE ROW LEVEL SECURITY;

INSERT INTO public.website_user_access (user_id, website_id, granted_by)
SELECT w.user_id, w.id, w.user_id
FROM public.websites w JOIN public.users u ON u.id = w.user_id
WHERE u.role <> 'super-admin' AND w.deleted_at IS NULL
ON CONFLICT (user_id, website_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.hero_slides AS
SELECT w.id AS website_id
FROM public.websites w
WITH NO DATA;

ALTER TABLE public.hero_slides
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS position smallint NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS badge_text varchar(120),
  ADD COLUMN IF NOT EXISTS badge_color varchar(20) NOT NULL DEFAULT 'teal',
  ADD COLUMN IF NOT EXISTS headline varchar(180),
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS image_path text,
  ADD COLUMN IF NOT EXISTS image_name varchar(255),
  ADD COLUMN IF NOT EXISTS image_type varchar(120),
  ADD COLUMN IF NOT EXISTS image_size bigint,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.hero_slides ALTER COLUMN website_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'hero_slides_pk') THEN
    ALTER TABLE public.hero_slides ADD CONSTRAINT hero_slides_pk PRIMARY KEY (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'hero_slides_website_fk') THEN
    ALTER TABLE public.hero_slides ADD CONSTRAINT hero_slides_website_fk
      FOREIGN KEY (website_id) REFERENCES public.websites(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'hero_slides_position_check') THEN
    ALTER TABLE public.hero_slides ADD CONSTRAINT hero_slides_position_check CHECK (position BETWEEN 1 AND 3);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS hero_slides_website_position_uq ON public.hero_slides (website_id, position);
CREATE INDEX IF NOT EXISTS hero_slides_public_idx ON public.hero_slides (website_id, is_active, position);
ALTER TABLE public.hero_slides ENABLE ROW LEVEL SECURITY;

-- Seed fixed slots for existing websites; the slots start empty and hidden.
INSERT INTO public.hero_slides (website_id, position, badge_color, is_active)
SELECT w.id, slot.position, CASE slot.position WHEN 2 THEN 'emerald' WHEN 3 THEN 'amber' ELSE 'teal' END, false
FROM public.websites w CROSS JOIN generate_series(1, 3) AS slot(position)
ON CONFLICT (website_id, position) DO NOTHING;

-- Move existing banner copy into the new dedicated module without deleting the
-- legacy profile columns. The first Beranda image becomes Slide 1's background.
UPDATE public.hero_slides hs
SET headline = COALESCE(hs.headline, wp.banner_title),
    description = COALESCE(hs.description, wp.banner_subtitle),
    is_active = COALESCE(hs.is_active, false) OR NULLIF(btrim(wp.banner_title), '') IS NOT NULL,
    updated_at = now()
FROM public.wilayah_profiles wp
WHERE hs.website_id = wp.website_id AND hs.position = 1
  AND hs.headline IS NULL AND hs.description IS NULL
  AND (wp.banner_title IS NOT NULL OR wp.banner_subtitle IS NOT NULL);

UPDATE public.hero_slides hs
SET image_path = COALESCE(asset.item ->> 'url', asset.item ->> 'path'),
    image_name = asset.item ->> 'name',
    image_type = asset.item ->> 'type',
    image_size = CASE WHEN (asset.item ->> 'size') ~ '^[0-9]+$' THEN (asset.item ->> 'size')::bigint ELSE NULL END,
    updated_at = now()
FROM public.contents c
JOIN public.menu_items m ON m.id = c.menu_item_id AND m.slug = 'beranda'
CROSS JOIN LATERAL (
  SELECT item
  FROM jsonb_array_elements(CASE WHEN jsonb_typeof(c.images) = 'array' THEN c.images ELSE '[]'::jsonb END) AS image_items(item)
  WHERE COALESCE(item ->> 'url', item ->> 'path') IS NOT NULL
  LIMIT 1
) asset
WHERE hs.website_id = c.website_id AND hs.position = 1 AND hs.image_path IS NULL;

UPDATE public.contents c
SET title = 'Profil Wilayah',
    body = NULLIF(concat_ws(E'\n\n', NULLIF(btrim(wp.visi), ''), NULLIF(btrim(wp.misi), '')), ''),
    updated_at = now()
FROM public.menu_items m, public.wilayah_profiles wp
WHERE c.menu_item_id = m.id AND m.slug = 'profil' AND c.website_id = wp.website_id
  AND (c.title = wp.banner_title OR c.body = wp.banner_subtitle);
